### PR TITLE
Add support for CMUCL

### PR DESCRIPTION
**Pull request by digikar99**

### CODE REVIEW

**Comment by digikar99** [comment]
The existing `(kernel:std-compute-class-precedence-list sub)` does not work correctly for structures; alternative is `(pcl:compute-class-precedence-list sub)`. A test for this: `(subctypep (specifier-ctype 'pathname) (specifier-ctype 'pathname))`.

**Comment by Bike** [comment]
Is there not just a `class-precedence-list` reader to use from the MOP?

**Comment by digikar99** [comment]
I'm not familiar with the internals, but, on CMUCL

```lisp
CL-USER> (apropos "class-precedence")
PCL::CLASS-PRECEDENCE-DESCRIPTION-P [function] 
PCL::COPY-CLASS-PRECEDENCE-DESCRIPTION [function] 
PCL::EARLY-CLASS-PRECEDENCE-LIST [function] (class)
PCL::CLASS-PRECEDENCE-DESCRIPTION [class] 
PCL:CLASS-PRECEDENCE-LIST [function] 
PCL:COMPUTE-CLASS-PRECEDENCE-LIST [function] 
KERNEL:STD-COMPUTE-CLASS-PRECEDENCE-LIST [function] (class)
```

OTOH, on SBCL:

```lisp
CL-USER> (apropos "class-precedence")
SB-PCL::%CLASS-PRECEDENCE-LIST
SB-PCL::CLASS-PRECEDENCE-DESCRIPTION
SB-PCL::CLASS-PRECEDENCE-DESCRIPTION-P (fbound)
SB-MOP:COMPUTE-CLASS-PRECEDENCE-LIST (fbound)
SB-PCL::EARLY-CLASS-PRECEDENCE-LIST (fbound)
SB-KERNEL:STD-COMPUTE-CLASS-PRECEDENCE-LIST (fbound)
SB-MOP:CLASS-PRECEDENCE-LIST (fbound)
```

So, `pcl:class-precedence-list` on CMUCL looks like the closest candidate to `sb-mop:class-precedence-list`.

**Comment by Bike** [comment]
Probably. These are part of MOP, which is an extension to the standard. `class-precedence-list` returns the existing class precedence list while `compute-class-precedence-list` computes it again, so we want to use the former. The closer to MOP portability library uses `clos-mop:class-precedence-list` on CMUCL, which might be an alias or something? https://github.com/pcostanza/closer-mop/blob/master/closer-mop-packages.lisp#L77

**Comment by digikar99** [comment]
Yup the alias does exist on CMUCL: `(eq 'closer-mop:class-precedence-list 'pcl:class-precedence-list) ;=> T`

**Pull request merged**
