### PR TITLE
Automate config

### PR DESCRIPTION
**Pull request by digikar99**
I wanted to add support for CCL; but felt quite a few parts could be automated.

Currently, the remaining parts include: 

- [ ] standard-charset: I didn't get the syntax, what number corresponds to what?
- [ ] string-uaets: Again, syntax; why is `nil` included in sbcl but not clasp (does clasp not support arrays with element-type `nil`?)
- [x] ~~base-charset~~ 
- [ ] class-aliases: I don't have an idea to automate it at least at the moment
- [ ] complex-ucptp: Again, syntax: I am unable to get what corresponds to what

### CODE REVIEW

**Comment by Bike** [comment]
I defined those parts of the config to not use the implementation `typep` in order to facilitate using this library as _the_ implementation of `typep`. Ditto `subtypep`. The standard does not guarantee that base chars are contiguous or start at zero, so your automation there is technically incorrect, although it probably works on any actual implementation.

> standard-charset: I didn't get the syntax, what number corresponds to what?

It's the same kind of input as the base charset, and you got the format there right. You have a list of conses and each cons represents a range of character codes. `((10 . 10) (32 . 126))` means that character codes 10, 32, 33, ... 125, 126 are the standard characters. `(32 . 126)` encompasses ASCII's letters, numbers, and some punctuation, and `10` is the newline character.

> string-uaets: Again, syntax; why is nil included in sbcl but not clasp (does clasp not support arrays with element-type nil?

Correct.

> complex-ucptp: Again, syntax: I am unable to get what corresponds to what

Yes, this one is confusing, sorry. The idea is that `(typep object '(complex foo))` is equivalent to `(complex-ucptp object ufoo)`, where ufoo is `(upgraded-complex-part-type 'foo)`.

**Comment by digikar99** [comment]
> to facilitate using this library as the implementation of `typep`

I see, okay! That makes sense.

> does not guarantee that base chars are contiguous or start at zero

and 

> a list of conses and each cons represents a range of character codes

sums things up.

> complex-ucptp

That looks understandable now. Is there a reason why that is a macro?

I could issue another PR for adding support for CCL then, and perhaps also add comments / commented-code from this discussion as guidance for anyone adding support for more implementations in the future.

**Comment by Bike** [comment]
It's a macro because if you know the upgraded complex part type statically you don't need to branch on it or anything. e.g. in sbcl you can see there are distinct functions for different part types, so you can just pick the correct one at compile time.

**Comment by digikar99** [comment]
I see, just optimization (?)

**Comment by Bike** [comment]
Yeah, I suppose. I mean there's no point doing a runtime switch if you don't have to.

**Pull request closed without merging**
